### ISSUE TITLE
Create nlmod organisation and add nlmod repo to this

### ISSUE THREAD

**Issue by OnnoEbbens** [gwmod/nlmod#221]

**Comment by OnnoEbbens** [comment]
I was trying to create the nlmod organisation but it already exists. It was created on 2 september 2022. Maybe someone of us created this? @bdestombe, @dbrakenhoff?

**Comment by bdestombe** [comment]
Hi Onno, neither Davíd or me has created the organization. Maybe you could
reach out to GitHub to see who is in charge of this organization?

**Comment by OnnoEbbens** [comment]
Okay, I will send a mail to Github

**Comment by OnnoEbbens** [comment]
Just got a message from GitHub:

> Hi there,
> 
> GitHub’s Username Policy has recently been updated and we are no longer accepting requests to release dormant usernames. We are not able to accommodate this request.
> 
> [You can read our policy here](https://docs.github.com/en/github/site-policy/github-username-policy)
> 
> Please note, it is not possible to determine if an account is inactive based on publicly-exposed information. We cannot contact account owners on your behalf or share their contact details with you.
> 
> If you hold a trademark to this name and believe there is a clear case of confusion between the account and your trademark, please review our [Trademark Policy](https://docs.github.com/articles/github-trademark-policy/) to determine if you should submit a trademark policy violation report.
> 
> Best,
> GitHub Support

So I think we will have to find another name for the organization. Any suggestions?

**Comment by bdestombe** [comment]
What about putting it in the worldmod organization and let nlmod be a first
package?

**Comment by rubencalje** [comment]
Are we really sure none of us made the user `nlmod`? You can test some of your email-adresses in the signup-process:

https://github.com/signup/

If you have a GitHub-account on the address you filled in, it is not possible to add another GitHub-account.

Otherwise, it can be an opportunity to add the word groundwater in the name, as `nlmod` lacks this. So I propose: `gwmod`. I prefer this over `worldmod`.

**Comment by rubencalje** [comment]
I just claimed the organisation name `gwmod`, just to be sure. However, it is not my intention to force this discussion, so this is not the final name.

**Comment by OnnoEbbens** [comment]
For me `worldmod` and `gwmod` are both fine with me. `gwmod` is more specific so that may be a reason to choose it.

**Comment by bdestombe** [comment]
Great find! I am also in favor of gwmod ;)
______________
Bas F. des Tombe
+31 6 461 94 706


Op ma 16 okt 2023 om 10:16 schreef OnnoEbbens ***@***.***>:

**Comment by rubencalje** [comment]
Yesterday I transferred the repository to the organization `gwmod`. Everything seems to be working fine. When going to the old location (https://github.com/ArtesiaWater/nlmod) you will be redirected to the new one (https://github.com/gwmod/nlmod). Github Desktop automatically changed the link from my local copy.

Please give a signal here if there are problems.

**Comment by dbrakenhoff** [comment]
Check the remote URL for your git repository with `git remote -v`

And if necessary, use the following to update remotes manually (this url is for SSH):

`git remote set-url origin git@github.com:gwmod/nlmod.git`

**Comment by OnnoEbbens** [comment]
No problems were reported after moving the repo, good job!
