### ISSUE TITLE
set_ds_time changes ds inplace

### ISSUE THREAD

**Issue by bdestombe** [gwmod/nlmod#274]
Most of the other functionality returns a Dataset that can be used to update ds, however the set_ds_time function in dims/time.py is one of the few that changes ds inplace.

**Comment by dbrakenhoff** [comment]
I can confirm the original input dataset is not modified. A new dataset is returned containing a "time" coordinate and data variables "steady", "nstp" and "tsmult".

If this is also working for you @bdestombe, we can close this issue I think.

**Comment by bdestombe** [comment]
Thanks guys. I cannot reproduce it anymore..
