### ISSUE TITLE
grid  refinement with shapefile

### ISSUE THREAD

**Issue by jeroenhelder** [gwmod/nlmod#303]
Hi,

when using a shapefile for gridrefinement I receive an error: assert os.path.isfile(sn), f"Shapefile does not exist: {sn}"
Apparently the add_refinement_features function searches for the existence of the shapefile with an extra .shp extension.
changing line 446 seems to solve the problem (at least for me)

sn = os.path.join(self.model_ws, f"{shapefile}")

**Comment by OnnoEbbens** [comment]
Thanks for pointing this out Jeroen. We use the gridgen module from the flopy package to do the grid refinement. The lines you mention are inside this module and not in the nlmod package. So I think the best way to go is to create an issue in the flopy package.

**Comment by OnnoEbbens** [comment]
I opened an issue in the flopy package (https://github.com/modflowpy/flopy/issues/2024). I will close this issue
