### ISSUE TITLE
HHNK peilgebieden rest not working

### ISSUE THREAD

**Issue by OnnoEbbens** [gwmod/nlmod#308]
The rest api to get peilbgebieden for HHNK has been changed which causes an error. In the new configuration a layer should be combined with a table to get the water levels per level area. I started with this in commit b0f6e9c4357d0e4639439fac6a2b5adb0eb3f0d8 but I have not implemented it completely yet.

Some things that still need to be done:
- figure out how to interpret the numbers 901 t/m 906 of the SOORTSTREEFPEIL column.
- Add the different levels from the WATERHOOGTE column to the geodataframe based on the PEILGEBIEDVIGERENDID
- Seperate settings for this in the config and logic in the `arcrest` function

**Comment by bdestombe** [comment]
#314 and #317

**Comment by bdestombe** [comment]
Superseded by #320
