### ISSUE TITLE
Move parts of webservices.py to waterboards.py

### ISSUE THREAD

**Issue by bdestombe** [gwmod/nlmod#317]
Ah I understand. I should have put the logic for waterboards in waterboards.py and not in webservices.py. I don't remember why I did that. I can fix this, but unfortunately not anytime soon. For now we can merge this as a quick fix and leave an issue open for me to fix this correctly later.

_Originally posted by @OnnoEbbens in https://github.com/gwmod/nlmod/issues/314#issuecomment-1906460100_

**Comment by OnnoEbbens** [comment]
fixed in the dev branch
