### ISSUE TITLE
Not all files are installed

### ISSUE THREAD

**Issue by vincentpost** [gwmod/nlmod#342]
Hi team,

When installing nlmod using pip install, it seems that not all necessary files in the repository are being copied over. I noticed that the voleg and gleg files in the data/geotop directory are missing on my machine (only the csv files are there). Any clues?

Thanks!

**Comment by rubencalje** [comment]
You are right. Only csv-files were specified in the install-file (pyproject.toml). I will add a fix.

**Comment by vincentpost** [comment]
Thanks Ruben, I just tested this and it works
