### ISSUE TITLE
Problem downloading data from REGIS and GeoTOP in tests and documentation 

### ISSUE THREAD

**Issue by rubencalje** [gwmod/nlmod#353]
There are problems with downloading REGIS and GeoTOP in the tests and the documentation-website. I think this is related to the version (1.7.0 or 1.71) of the netCDF4-package, see https://github.com/Unidata/netcdf4-python/issues/1335.

I will set the version of netCDF4 to below 0.7.0 for the tests and the doucmentation, until the issue is fixed.

**Comment by dbrakenhoff** [comment]
Closed by #352
