### ISSUE TITLE
REGIS dataset has changed

### ISSUE THREAD

**Issue by bdestombe** [gwmod/nlmod#362]
Suddenly, hydraulica conductivities of -9999 are popping up in the REGIS retreived data. The nlmod tests are failing and so do all models using REGIS.

**Comment by rubencalje** [comment]
You are right... There seems to be a new update of REGIS:
https://www.dinoloket.nl/nieuws/regis-ii-kleine-release-omgeving-leersum-amerongen-en-omgeving-cuijk

The new dataset contains -9999 instead of NaN-values. I think we should make a new update this week. I will see if I can quickly fix it.

**Comment by rubencalje** [comment]
I have just updated the main branch and released version 0.8.1, where this issue should be fixed.

**Comment by bdestombe** [comment]
That was quick Ruben! Thank you so much

**Comment by dbrakenhoff** [comment]
Fixed by 9bcbc73156b5b8b759b0a4ea3b355dcca0b8c0d6
