### ISSUE TITLE
Add support for Algemeen Hoogtebestand Nederland versie 5 (AHN5)

### ISSUE THREAD

**Issue by martinvonk** [gwmod/nlmod#367]
AHN5 is released in 2023 for northwest part of the Netherlands and more recently for the western part of the Netherlands. The southern part will be available in 2024, and the northeastern part in 2025: https://www.ahn.nl/tweede-deel-ahn5-beschikbaar
![map](https://cuatro.sim-cdn.nl/ahn/uploads/styles/wysiwyg_medium/media/vliegkaart_2.jpg?cb=RQ7dfE8Z)

Maybe we can add support for the already available tiles in the AHN5:
DTM_WMS: https://api.ellipsis-drive.com/v3/ogc/wms/51e11c02-1065-463d-a0b0-263d80293b16
DTM_WMTS: https://api.ellipsis-drive.com/v3/ogc/wmts/51e11c02-1065-463d-a0b0-263d80293b16
DTM_WCS: https://api.ellipsis-drive.com/v3/ogc/wcs/51e11c02-1065-463d-a0b0-263d80293b16

DSM_WMS: https://api.ellipsis-drive.com/v3/ogc/wms/a4a8a27b-e36e-4dd5-a75b-f7b6c18d33ec
DSM_WMTS: https://api.ellipsis-drive.com/v3/ogc/wmts/a4a8a27b-e36e-4dd5-a75b-f7b6c18d33ec
DSM_WCS: https://api.ellipsis-drive.com/v3/ogc/wcs/a4a8a27b-e36e-4dd5-a75b-f7b6c18d33ec

Tiles example for 38DN1:
LAZ: https://ns_hwh.fundaments.nl/hwh-ahn/AHN5/01_LAZ/2023_C_38DN1.LAZ
DTM 0.5m: https://ns_hwh.fundaments.nl/hwh-ahn/AHN5/02a_DTM_50cm/2023_M_38DN1.TIF
DTM 5.0m: https://ns_hwh.fundaments.nl/hwh-ahn/AHN5/02b_DTM_5m/2023_M5_38DN1.TIF
DSM 0.5m: https://ns_hwh.fundaments.nl/hwh-ahn/AHN5/03a_DSM_50cm/2023_R_38DN1.TIF
DSM 5.0m: https://ns_hwh.fundaments.nl/hwh-ahn/AHN5/03b_DSM_5m/2023_R5_38DN1.TIF

Nice gimmick:
Vlieglijnen: https://api.ellipsis-drive.com/v3/ogc/wfs/a4a8a27b-e36e-4dd5-a75b-f7b6c18d33ec
Vlieglijnen features: https://api.ellipsis-drive.com/v3/ogc/features/a4a8a27b-e36e-4dd5-a75b-f7b6c18d33ec

**Comment by dbrakenhoff** [comment]
Added by #370
