### ISSUE TITLE
Download ahn produces only zeros with rasterio version 1.3.11

### ISSUE THREAD

**Issue by rubencalje** [gwmod/nlmod#369]
Showing warning:

> WARNING:py.warnings._showwarnmsg:C:\Users\Ruben\miniconda3\envs\artesia\lib\site-packages\rasterio\merge.py:321: UserWarning: Ignoring nodata value. The nodata value, 3.4028234663852886e+38, cannot safely be represented in the chosen data type, float32. Consider overriding it using the --nodata option for better results. Falling back to first source's nodata value.

**Comment by dbrakenhoff** [comment]
Fixed by #370

**Comment by bdestombe** [comment]
The ellipsis server used in the new method introduced in #370 seems to lack a few tiles. Some urls are nan's leading to errors further down the line.
![image](https://github.com/user-attachments/assets/8957a4a6-8aec-4564-b41e-746fac32d22c)

**Comment by rubencalje** [comment]
Nice catch.

I think it is just the tile in the northsea, that has been renamed between version 2 and 3 of ahn, I guess. See the location of tiles 72Hz2 and 18HZ2 below. I will add a check that ignores nan-values in the tile-names. This is probably also needed for AHN 5 probably, which is not defined everywhere in the Netherlands jet.

![18HZ2](https://github.com/user-attachments/assets/cadc8981-80e5-4334-9dd8-0d0d1944235e)
![72HZ2](https://github.com/user-attachments/assets/ccc96ae5-9c45-41d1-9a12-ac8b49099829)

**Comment by bdestombe** [comment]
#371

**Comment by bdestombe** [comment]
Closed with #371
