### ISSUE TITLE
Make use of flopy's support for multipolygons in grid intersection

### ISSUE THREAD

**Issue by bdestombe** [gwmod/nlmod#391]
https://github.com/gwmod/nlmod/blob/fc6d4ae7554a28bf3d7af2ba2703b37b5a7c614b/nlmod/dims/grid.py#L1718

We could remove the for-loop here. The first line in the code below reads a geopandas dataframe with polygons. The second line transforms all polygons into a single multipolygon.

```python
from shapely.ops import unary_union

gdf_mask = gpd.read_file(fp_mask)
multipolygon = unary_union(gdf_mask.geometry)

r = ix.intersect(multipolygon).astype([
    ("icell2d", int),
    ("ixshapes", "O"),
    ("areas", float),
])
```

**Comment by dbrakenhoff** [comment]
Note that flopy will support returning the intersection results as a (geo)dataframe in future versions using `geo_dataframe=True` in the `intersect()` call or `dataframe=True` in the `intersects()` call.

**Comment by bdestombe** [comment]
#396
