### ISSUE TITLE
failing test `bgt_bronhoudername`

### ISSUE THREAD

**Issue by OnnoEbbens** [gwmod/nlmod#394]
`test_bgt_waterboards` fails when trying to add bronhoudername, see: https://github.com/gwmod/nlmod/actions/runs/12350606768/job/34463823067

It fails somewhere in this code:
```
dates = to_datetime(
        [
            "-".join(x.rsplit("-", 3)[-3:])
            for x in tree.xpath("//a/@href")
            if "bronhoudercodes" in x
        ],
        format="%d-%m-%Y",
    )
```

**Comment by martinvonk** [comment]
The kadaster put an extra dash `-` in the url... :(
https://www.kadaster.nl/-/bgt-bronhoudercodes-per-1-1-2025-
